package com.example.diaryapp.db;

import java.util.HashMap;

public class QuestionList {

    private static HashMap<String, String> questions = new HashMap<>();

    public static HashMap<String, String> getQuestions(){
        if(questions.size() == 0){
            setQuestions();
        }
        return questions;
    }

    private static void setQuestions(){
        //1월
        questions.put("0101", "내 삶의 목적은 무엇인가?");
        questions.put("0102", "사람은 변할 수 있을까?");
        questions.put("0103", "현재 읽고 있는 글이나 책이 있다면?");
        questions.put("0104", "내 삶에서 가장 결별하고 싶은 것은?");
        questions.put("0105", "가장 최근에 방문한 식당은? 무엇을 먹었는가?");
        questions.put("0106", "오늘 하루가 힘들었던 이유는 _____이다.");
        questions.put("0107", "나는 운이 좋은 편이라고 생각하는가?");
        questions.put("0108", "계속 머릿속에 맴도는 노래가 있다면?");
        questions.put("0109", "오늘은 평범한 하루였는가? 그렇거나 그렇지 않은 이유는?");
        questions.put("0110", "내 인생을 바꿀 만한 영감을 준 사람이 있다면?");
        questions.put("0111", "나는 오늘 _____을(를) 잃었다.");
        questions.put("0112", "가장 좋아하는 액세서리는?");
        questions.put("0113", "다음에 여행하고 싶은 곳은 어디인가?");
        questions.put("0114", "나는 이끄는 쪽인가 따르는 쪽인가?");
        questions.put("0115", "가장 자신있게 만들 수 있는 요리는?");
        questions.put("0116", "빌리거나 빌려준 돈이 있는가?");
        questions.put("0117", "오늘 입은 옷차림 중에서 가장 오래된 것은?");
        questions.put("0118", "최근 꾼 꿈 중에 가장 인상적인 것은?");
        questions.put("0119", "평생 한 사람만 사랑하면서 살 수 있다고 생각하는가?");
        questions.put("0120", "앙심을 품고 있는 대상이 있는가? 무슨 일 때문인가?");
        questions.put("0121", "만약 창업을 한다면 어떤 일을 하고 싶은가?");
        questions.put("0122", "안전을 추구하는가 모험을 추구하는가?");
        questions.put("0123", "휴식이 필요하다고 느끼는가? 무엇으로부터?");
        questions.put("0124", "몹시 기다려지는 일이 있는가?");
        questions.put("0125", "무엇이 나를 나답게 만드는가?");
        questions.put("0126", "오늘 나는 _____이(가) 좀 더 필요했다.");
        questions.put("0127", "오늘의 나를 예술사조로 표현한다면? (초현실주의, 모더니즘, 다다이즘)");
        questions.put("0128", "집이란 무엇이라고 생각하는가?");
        questions.put("0129", "마지막으로 본  TV 프로그램은?");
        questions.put("0130", "오늘 있었던 일 중에서 지우고 싶은 기억이 있다면?");
        questions.put("0131", "궁극적으로 어떤 사람이 되고 싶은가?");

        //2월
        questions.put("0201", "내일 무엇을 할 계획인가?");
        questions.put("0202", "누구와 함께 사는가?");
        questions.put("0203", "오늘 하루 슬퍼할 일이 있었는가? 그 강도를 1에서 10으로 표현한다면?");
        questions.put("0204", "지금 밖의 날씨는 _____(이)다.");
        questions.put("0205", "친구란 _____(이)다.");
        questions.put("0206", "가장 위대하다고 생각하는 직업은?");
        questions.put("0207", "당장 갖고 싶은 세가지가 있다면?");
        questions.put("0208", "만 원을 가장 알차게 쓸 수 있는 방법은 무엇일까?");
        questions.put("0209", "어제 몇 시에 잠자리에 들었는가?");
        questions.put("0210", "오늘 하루를 동물에 비유한다면? 그 이유는 무엇인가?");
        questions.put("0211", "오늘 무엇을 타고 출근했는가?");
        questions.put("0212", "현재 나의 꿈을 가로막는 가장 큰 장애물은 무엇인가?");
        questions.put("0213", "사람들에게 가장 즐겨하는 질문은 무엇인가?");
        questions.put("0214", "지금 사랑하고 있는가?");
        questions.put("0215", "상처받은 마음을 치유하는 나만의 방법을 적어보자.");
        questions.put("0216", "마지막으로 가본 공연이나 콘서트는?");
        questions.put("0217", "오늘 하루 벌어진 일 중에서 바꾸고 싶은 게 있다면?");
        questions.put("0218", "지금 몸에 걸친 것 중에서 가장 비싼 물건은?");
        questions.put("0219", "내가 아는 가장 정신나간 사람은 누구인가?");
        questions.put("0220", "오늘 지나치게 많이 사용한 말은?");
        questions.put("0221", "요즘 유행하는 말을 세 개만 적어보자.");
        questions.put("0222", "오늘 가장 두드러진 감정은 무엇인가?");
        questions.put("0223", "최근 신용카드 결제 내역에서 가장 당혹스러운 항목은?");
        questions.put("0224", "오늘 _____(이)가 지나치게 많았다.");
        questions.put("0225", "오늘 하루 간절히 원했지만 얻지 못한 것이 있다면?");
        questions.put("0226", "절대로 버릴 수 없는 물건을 하나만 적어보자.");
        questions.put("0227", "나는 독창적인 사람인가 받아들이는 사람인가?");
        questions.put("0228", "마지막으로 아팠던 적은 언제인가?");
        questions.put("0229", "오늘은 4년마다 돌아오는 특별한 날이다. 하루를 어떻게 보냈는가?");

        //3월
        questions.put("0301", "오늘 있었던 일 중 후회하는 것은?");
        questions.put("0302", "오늘 나의 하루는 짠맛인가, 달달한 맛인가?");
        questions.put("0303", "중학생으로 돌아간다면 하고 싶은 일은?");
        questions.put("0304", "어머니께 하고 싶은 질문은?");
        questions.put("0305", "지금 이 순간 가장 좋아하는 단어는?");
        questions.put("0306", "나의 원수는 누구인가?");
        questions.put("0307", "_____을(를) 실험하는 것은 좋은 생각이 아니다.");
        questions.put("0308", "마지막으로 들은 노래는?");
        questions.put("0309", "오늘 무시하고 싶었던 사람은 _____(이)다.");
        questions.put("0310", "가장 최근에 본 영화는?");
        questions.put("0311", "생일선물로 절대 받고 싶지 않은 것이 있다면?");
        questions.put("0312", "어디에 사는가?");
        questions.put("0313", "하루에 한 시간이 늘어난다면 뭘 할까?");
        questions.put("0314", "부인할 수 없는 사실은 무엇인가?");
        questions.put("0315", "아무에게도 하고 싶지 않은 이야기가 있는가?");
        questions.put("0316", "지금 당장 사고 싶은 것은?");
        questions.put("0317", "오늘 처음 시도해본 활동이 있다면?");
        questions.put("0318", "무엇을 위해 기도하는가?");
        questions.put("0319", "나는 왜 일하는가?");
        questions.put("0320", "마지막으로 읽은 책은?");
        questions.put("0321", "오늘 가장 먼저 먹은 음식은?");
        questions.put("0322", "오늘의 뉴스 기사를 하나 적어보자.");
        questions.put("0323", "발라드와 댄스 중에 어떤 음악을 선택하겠는가?");
        questions.put("0324", "오늘 떠올린 생각 중에 가장 엉뚱한 것은?");
        questions.put("0325", "_____(이)가 나를 웃게 했다.");
        questions.put("0326", "이성을 만날 때 가장 중요하게 생각하는 조건은?");
        questions.put("0327", "마지막으로 가장 행복했을 때는 언제인가?");
        questions.put("0328", "오늘 하루 중 기억에 남기고 싶은 것은?");
        questions.put("0329", "나에게 없어서는 안 되는 인류의 발명품은?");
        questions.put("0330", "오늘을 색깔로 표현해보자.");
        questions.put("0331", "오늘 하루와 어울리는 시나 노래 구절을 적어보자.");

        //4월
        questions.put("0401", "내가 한 거짓말 중에 가장 큰 파장을 불러일으켰던 것은?");
        questions.put("0402", "남모르게 간직한 열정이 있다면?");
        questions.put("0403", "오늘 하루 즐거웠는가? 그 이유는?");
        questions.put("0404", "오늘 일어나기를 바라는 일은?");
        questions.put("0405", "죽기 전에 꼭 하고 싶은 일이 있다면?");
        questions.put("0406", "가장 최근에 주문한 테이크아웃 음식은?");
        questions.put("0407", "지금 어떤 색깔의 옷을 입고 있는가?");
        questions.put("0408", "비밀을 털어놓을 수 있는 사람을 한 명만 꼽는다면?");
        questions.put("0409", "가장 편안하게 느껴지는 장소는?");
        questions.put("0410", "오늘 빼먹은 집안일은 _____(이)다.");
        questions.put("0411", "오늘 나를 가장 기쁘게 한 소식은 무엇인가?");
        questions.put("0412", "요즘 관심 있는 정치적 이슈는?");
        questions.put("0413", "일요일 오전을 행복하게 보내는 나만의 비법은?");
        questions.put("0414", "(노력없이) 한 가지 재능을 얻을 수 있다면 무엇을 고르겠는가?");
        questions.put("0415", "인터뷰하고 싶은 유명인사는?");
        questions.put("0416", "오늘 새롭게 알게 된 사실을 적어보자.");
        questions.put("0417", "나의 가장 큰 단점은 무엇인가?");
        questions.put("0418", "오늘 해결한 문제를 한 가지만 적어보자,");
        questions.put("0419", "세상을 떠난 유명인 중에서 저녁식사를 함께하고 싶은 사람은?");
        questions.put("0420", "오늘 몇 번이나 욕했는가?");
        questions.put("0421", "누군가 \"무슨 일 하세요?\"라고 물을 때 뭐라고 답하는가?");
        questions.put("0422", "절대 일어나지 않았으면 하는 일은?");
        questions.put("0423", "부모님은 나를 어떻게 생각하실까?");
        questions.put("0424", "인생은 공평하다고 생각하는가?");
        questions.put("0425", "지금 당장 전화를 걸고 싶은 사람은?");
        questions.put("0426", "현재 지갑에 돈이 얼마나 있는가?");
        questions.put("0427", "나는 감성적인 사람인가, 이성적인 사람인가?");
        questions.put("0428", "딱 하루만 인생을 바꿀 수 있다면 누구와 바꾸겠는가?");
        questions.put("0429", "내가 행복하게 만들어줄 수 있는 사람은 누구일까?");
        questions.put("0430", "오늘 하루를 세 단어로 표현한다면?");

        //5월
        questions.put("0501", "가장 좋아하는 꽃이나 식물이 있다면?");
        questions.put("0502", "나는 깔끔한 사람인가, 지저분한 사람인가?");
        questions.put("0503", "하루 동안 초능력을 가질 수 있다면 어떤 것을 원하는가?");
        questions.put("0504", "마지막으로 수영을 한 적은 언제인가?");
        questions.put("0505", "정말 신나는 하루였다. 그 이유는 _____이다.");
        questions.put("0506", "좋은 적이란 과연 존재할까?");
        questions.put("0507", "내 인생을 영화로 만든다면 주인공 역은 누구로 하고 싶은가?");
        questions.put("0508", "어머니께 하고 싶은 말은?");
        questions.put("0509", "오늘 해야 할 일 중 미루고 싶은 일은 무엇인가?");
        questions.put("0510", "오늘 하루를 어떻게 시작했는가?");
        questions.put("0511", "최근에 한 가장 창의적인 일은?");
        questions.put("0512", "현재 탐구하고 있는 분야가 있다면?");
        questions.put("0513", "오늘 나에게 애정을 보여준 사람은?");
        questions.put("0514", "마지막으로 참석한 모임은?");
        questions.put("0515", "지금까지 이룬 것 중 성취감이 가장 컸던 일은?");
        questions.put("0516", "무슨 요일을 가장 좋아하는가? 그 이유는?");
        questions.put("0517", "나는 오늘 _____을(를) 제거했다.");
        questions.put("0518", "타임머신을 타고 과거로 돌아가 꼭 바꾸고 싶은 일이 있다면?");
        questions.put("0519", "주변인의 죽음 중 가장 슬펐던 사람은?");
        questions.put("0520", "사랑을 위해 저지른 가장 정신 나간 짓은?");
        questions.put("0521", "내 연봉은 얼마인가?");
        questions.put("0522", "가장 최근에 말다툼을 한 적이 있는가? 무슨 일 때문이었나?");
        questions.put("0523", "현재 나의 헤어스타일은?");
        questions.put("0524", "오늘 나에게 동기를 부여해준 일은?");
        questions.put("0525", "내일 어디든 여행할 수 있다면 가고 싶은 곳은?");
        questions.put("0526", "오늘 나를 괴롭힌 일들을 적어보자.");
        questions.put("0527", "현재 나에게 위안을 주는 것은?");
        questions.put("0528", "산과 바다 중 어느 곳이 더 좋은가?");
        questions.put("0529", "휴가가 하루 주어진다면 무엇을 하고 싶은가?");
        questions.put("0530", "오늘 읽은 가장 인상적인 글귀는?");
        questions.put("0531", "현재 지갑에 얼마가 있는가?");

        //6월
        questions.put("0601", "나의 건강 상태를 1에서 10으로 나타낸다면?");
        questions.put("0602", "직감을 믿는 편인가?");
        questions.put("0603", "지금 이 순간 가장 그리운 사람은?");
        questions.put("0604", "오늘 나는 _____을(를) 입었다.");
        questions.put("0605", "마지막으로 먹은 과일은 무엇인가?");
        questions.put("0606", "가족 중 가장 가까운 사람은?");
        questions.put("0607", "오늘 감사하게 생각하는 일은?");
        questions.put("0608", "나를 불행하게 만드는 것은?");
        questions.put("0609", "좋은 친구란 무엇일까?");
        questions.put("0610", "오늘 커피를 몇 잔 마셨는가?");
        questions.put("0611", "금요일 밤을 보내는 나만의 가장 행복한 방법은?");
        questions.put("0612", "한 달안에 이루고 싶은 목표가 있는가?");
        questions.put("0613", "오늘 나를 걱정하게 만든 것은 _____(이)다.");
        questions.put("0614", "지속적으로 하고 있는 운동이 있는가?");
        questions.put("0615", "가장 좋아하는 전자기기는?");
        questions.put("0616", "나를 냉소적으로 만드는 것은?");
        questions.put("0617", "오늘 가장 좋았던 시간은 언제인가?");
        questions.put("0618", "누군가 나를 위해 요리해준 적이 있는가?");
        questions.put("0619", "가장 최근에 받은 손편지는 누구에게서 온 것인가?");
        questions.put("0620", "자서전을 쓴다면 첫 문장을 어떻게 쓰고 싶은가?");
        questions.put("0621", "더 가까워지고 싶은 사람이 있다면?");
        questions.put("0622", "가장 최근에 영화관에서 본 영화는?");
        questions.put("0623", "마지막으로 울었던 적은 언제인가?");
        questions.put("0624", "조만간 참여해야 하는 모임이나 행사는?");
        questions.put("0625", "전쟁이 일어날 것이라고 생각하는가?");
        questions.put("0626", "제일 무서워하는 것은?");
        questions.put("0627", "마지막으로 피자를 먹은 적이 언제인가? 어떤 피자였는가?");
        questions.put("0628", "날씨 예보처럼 기분을 예측한다면 앞으로 내 기분은 ____(이)다.");
        questions.put("0629", "주량이 얼마나 되는가?");
        questions.put("0630", "딱 하루만 원하는 직업으로 살 수 있다면 무엇을 선택하겠는가?");

        //7월
        questions.put("0701", "마지막으로 가본 바다는?");
        questions.put("0702", "오늘 취소한 일은 _____(이)다.");
        questions.put("0703", "사랑과 우정 중에 하나를 고른다면?");
        questions.put("0704", "_____(은)는 재미있다.");
        questions.put("0705", "나의 신조는 무엇인가?");
        questions.put("0706", "가장 최근에 듣고 눈물을 흘린 노래는 무엇인가?");
        questions.put("0707", "최근에 가장 많이 웃었던 적은?");
        questions.put("0708", "내가 잃을 수밖에 없는 것은?");
        questions.put("0709", "오늘이 유쾌했던 이유는 _____(이))다.");
        questions.put("0710", "부모님과 마지막으로 대화를 나눈 적은 언제인가?");
        questions.put("0711", "닮고 싶은 문학작품 속 주인공은?");
        questions.put("0712", "_____(은)는 완벽하다.");
        questions.put("0713", "나를 감성에 젖게 만드는 것은?");
        questions.put("0714", "비밀이 있는가? 하나 이상인가?");
        questions.put("0715", "나의 아킬레스건은 무엇인가?");
        questions.put("0716", "지금 양말을 신고 있는가?");
        questions.put("0717", "나의 가장 큰 장점은?");
        questions.put("0718", "완벽한 하루를 위해서는 무엇이 필요할까?");
        questions.put("0719", "내가 버려야 할 것은 무엇인가?");
        questions.put("0720", "오늘 상처받은 일이 있는가?");
        questions.put("0721", "가장 최근에 나를 화나게 만든 사람은 누구인가?");
        questions.put("0722", "좋은 아이디어를 떠올려야 할 때 찾는 곳은?");
        questions.put("0723", "가장 최근에 만든 요리는?");
        questions.put("0724", "냉장고에 뭐가 들어있는가?");
        questions.put("0725", "(과거 또는 현존하는) 화가 중에서 초상화를 부탁하고 싶은 사람은?");
        questions.put("0726", "성실하게 일하는 편인가, 꾀를 부리는 편인가?");
        questions.put("0727", "지금 손에서 무슨 냄새가 나는가?");
        questions.put("0728", "오늘 하루가 힘들었던 이유는 _____(이)다.");
        questions.put("0729", "더위를 피하는 나만의 방법은?");
        questions.put("0730", "오늘 평소와 달랐던 점은 _____(이)다.");
        questions.put("0731", "무작정 다가가 말을 걸고 싶은 사람이 있는가?");

        //8월
        questions.put("0801", "차가운 물로 샤워하는게 좋은가, 뜨거운 물로 샤워하는게 좋은가?");
        questions.put("0802", "지금 있는 곳을 묘사해보자.");
        questions.put("0803", "내가 피노키오라면 나의 코는 지금 얼마나 길어졌을까?");
        questions.put("0804", "가장 최근에 비행기를 탄 적은?");
        questions.put("0805", "오늘 내가 망가뜨린 것은 _____(이)다.");
        questions.put("0806", "나를 한 단어로 표현한다면?");
        questions.put("0807", "최근에 가장 맛있었던 식사는?");
        questions.put("0808", "나는 돈을 충분히 버는가?");
        questions.put("0809", "마지막으로 보낸 문자 메시지를 적어보자.");
        questions.put("0810", "지금 도망치고 싶은 일이 있다면?");
        questions.put("0811", "여권에 스탬프가 몇 개나 찍혀 있는가?");
        questions.put("0812", "뷔페에서 가장 먼저 먹는 음식은?");
        questions.put("0813", "토요일 오전을 보내는 나만의 가장 행복한 방법은?");
        questions.put("0814", "오늘 해야 할 일을 모두 끝마쳤는가?");
        questions.put("0815", "내 몸 중에서 가장 마음에 드는 곳은?");
        questions.put("0816", "가장 답하기 좋아하는 질문은 무엇인가?");
        questions.put("0817", "5년 동안 교도소에 갇히게 된다면 입소 전 날 무엇을 하고 싶은가?");
        questions.put("0818", "가장 좋아하는 옷은?");
        questions.put("0819", "오늘 나를 가장 신경 쓰이게 한 것은 _____(이)다.");
        questions.put("0820", "나는 어느 팀에 소속되어 있는가?");
        questions.put("0821", "오늘 하루를 140자 내외로 표현해보자.");
        questions.put("0822", "매일 먹어도 질리지 않는 음식이 있다면?");
        questions.put("0823", "앞으로 일어날 일을 상상할 때 최선의 경우를 떠올리는 편인가, 최악의 경우를 떠올리는 편인가?");
        questions.put("0824", "창의성 발휘에 필요한 요소를 적어보자.");
        questions.put("0825", "아버지에게 하고 싶은 말은?");
        questions.put("0826", "현재 삶에서 가장 만족스러운 부분은?");
        questions.put("0827", "마지막으로 언제 운동했는가?");
        questions.put("0828", "나만의 승리 구호가 있다면?");
        questions.put("0829", "오늘 저녁으로 뭘 먹었는가?");
        questions.put("0830", "당장 기분을 좋게 하는 비법이 있는가?");
        questions.put("0831", "가장 최근에 참석한 결혼식은?");

        //9월
        questions.put("0901", "나는 가르치는 사람인가, 배우는 사람인가?");
        questions.put("0902", "내가 사는 집은 깔끔한가?");
        questions.put("0903", "신은 존재한다고 믿는가? 그 증거는?");
        questions.put("0904", "나는 5년 후에 어떤 모습일까?");
        questions.put("0905", "오늘 배운 것은 _____(이)다.");
        questions.put("0906", "마지막으로 본 유튜브 영상은?");
        questions.put("0907", "오늘 입은 옷 중에서 가장 새것은?");
        questions.put("0908", "가장 질투 나는 사람은?");
        questions.put("0909", "두려움 하면 떠오르는 것은?");
        questions.put("0910", "나를 혼동하게 만드는 것은 _____(이)다.");
        questions.put("0911", "초등학교 2학년생에게 해주고 싶은 조언은?");
        questions.put("0912", "지금 이 순간 무엇을 좇고 있는가?");
        questions.put("0913", "사소하지만 고질적인 문제를 하나 적어보자.");
        questions.put("0914", "나의 마지막 사랑은 _____(이)다.");
        questions.put("0915", "가장 좋아하는 단어가 있다면?");
        questions.put("0916", "최근에 새로 생긴 가족이 있다면?");
        questions.put("0917", "요즘 자주 먹는 군것질거리는?");
        questions.put("0918", "가장 즐겨 찾는 인터넷 사이트는?");
        questions.put("0919", "최근에 새로 가본 곳은?");
        questions.put("0920", "가장 좋아하는 TV 프로그램은?");
        questions.put("0921", "내 인생은 어느 길로 나아가고 있는가?");
        questions.put("0922", "최근에 들은 충격적인 소식은?");
        questions.put("0923", "오늘의 명언 한마디를 적어보자.");
        questions.put("0924", "가장 최근에 신나게 춤을 췄던 노래는?");
        questions.put("0925", "논리보다 직감에 의존하는 편인가?");
        questions.put("0926", "오늘 재미있었던 일은 _____(이)다.");
        questions.put("0927", "사람들의 무리한 부탁을 잘 거절하는 편인가?");
        questions.put("0928", "현재 얼마나 배가 고픈가?");
        questions.put("0929", "좋은 소식과 나쁜 소식 중에 무엇을 먼저 듣고 싶은가?");
        questions.put("0930", "나만의 기분 전환 방법은?");

        //10월
        questions.put("1001", "광적으로 좋아하는 분야가 있다면?");
        questions.put("1002", "긴 머리와 짧은 머리 중에 하나를 고르라면?");
        questions.put("1003", "내가 본 최악의 영화는?");
        questions.put("1004", "나의 삶을 세 단어로 요약해보자.");
        questions.put("1005", "나를 불안하고 초조하게 만드는 질문은?");
        questions.put("1006", "1년 내에 새로 사귄 친구가 있는가?");
        questions.put("1007", "오늘 내린 선택들에 만족하는가?");
        questions.put("1008", "나의 가장 큰 꿈은 무엇인가?");
        questions.put("1009", "나는 새로운 _____을(를) 원한다.");
        questions.put("1010", "최근에 기분 좋은 대화를 나눈 사람의 이름을 적어보자.");
        questions.put("1011", "머리를 감지 않고 버틴 최장 기록은?");
        questions.put("1012", "오늘 하루를 한 단어로 표현한다면?");
        questions.put("1013", "나는 _____에 인내심이 없다.");
        questions.put("1014", "내가 지나치게 자주 사용하는 단어는?");
        questions.put("1015", "출퇴근에 걸리는 시간은?");
        questions.put("1016", "이름을 바꿀 수 있다면 무엇으로 하고 싶은가?");
        questions.put("1017", "내가 가진 가장 값나가는 물건은?");
        questions.put("1018", "현존하는 유명인 중에서 술 한잔하고 싶은 사람은?");
        questions.put("1019", "가장 최근에 신용카드로 구입한 것은?");
        questions.put("1020", "내가 믿고 의지하는 사람은?");
        questions.put("1021", "새롭게 알게 된 단어가 있다면?");
        questions.put("1022", "아침에 눈뜨면 가장 먼저 하는 일은?");
        questions.put("1023", "가장 최근에 부재중 전화를 건 사람은?");
        questions.put("1024", "강아지와 고양이 중에 기르고 싶은 동물은?");
        questions.put("1025", "최근에 한 말실수가 있다면?");
        questions.put("1026", "가장 최근에 받은 선물은?");
        questions.put("1027", "나에게 주고 싶은 선물이 있다면?");
        questions.put("1028", "_____(은)는 정말 말도 안 된다.");
        questions.put("1029", "캠핑 vs 호텔 숙박?");
        questions.put("1030", "누군가의 행동을 더 이상 참기 어려울 때 사실대로 말할 수 있는가?");
        questions.put("1031", "첫눈이 내리면 가장 먼저 하고 싶은 일은?");

        //11월
        questions.put("1101", "오늘 하지 못한 일은 무엇인가?");
        questions.put("1102", "현재 가장 큰 지출을 차지하는 부분은?");
        questions.put("1103", "최근에 아기를 안아본 적이 있는가?");
        questions.put("1104", "오늘 _____을(를) 만들었다.");
        questions.put("1105", "앞으로도 쭉 변하지 않았으면 하는 것은?");
        questions.put("1106", "가장 듣기 좋은 칭찬은?");
        questions.put("1107", "나의 영웅은 누구인가?");
        questions.put("1108", "지루하게 느끼는 대화 주제는?");
        questions.put("1109", "제시간에 퇴근하는가?");
        questions.put("1110", "가장 매력적이라고 생각하는 목소리는?");
        questions.put("1111", "평소 피하려고 하는 것은 무엇인가?");
        questions.put("1112", "국경일로 정하고 싶은 날이 있다면?");
        questions.put("1113", "나를 잘 나타내주는 노래는?");
        questions.put("1114", "최근에 한 충동구매가 있다면?");
        questions.put("1115", "오늘 아침 기상은 _____했다.");
        questions.put("1116", "나의 집중력 지수를 0에서 10으로 나타내보자.");
        questions.put("1117", "나를 이루고 있는 특징 세 가지를 적어보자.");
        questions.put("1118", "내가 생각하는 꿈의 직장은?");
        questions.put("1119", "마지막으로 SNS에 접속한 때는?");
        questions.put("1120", "오늘 당장 끝마쳐야 하는 일은?");
        questions.put("1121", "가장 아끼는 신발은?");
        questions.put("1122", "현재 노력하고 있는 일은?");
        questions.put("1123", "가장 좋아하는 외식 메뉴는?");
        questions.put("1124", "나의 장례식에 부르고 싶은 사람을 적어보자.");
        questions.put("1125", "오늘 물을 얼마나 마셨는가?");
        questions.put("1126", "가족을 세 단어로 표현한다면?");
        questions.put("1127", "현재 나의 라이벌은 누구인가?");
        questions.put("1128", "현실에 안주하고 싶은가, 흥분되는 도전을 원하는가?");
        questions.put("1129", "지금 기분을 다섯 글자로 표현한다면?");
        questions.put("1130", "가장 좋아하는 책은?");

        //12월
        questions.put("1201", "내 묘비에 남기고 싶은 말은?");
        questions.put("1202", "여름이 좋은가, 겨울이 좋은가?");
        questions.put("1203", "현재 느끼는 행복을 1에서 10으로 표현한다면?");
        questions.put("1204", "나의 마지막이 어떨지 알고 싶은가?");
        questions.put("1205", "재산이 얼마나 있으면 행복할까?");
        questions.put("1206", "오늘 _____을(를) 얻었다.");
        questions.put("1207", "나는 내년에 어떤 모습일까?");
        questions.put("1208", "이 세상에서 가장 매력적이라고 생각하는 사람은?");
        questions.put("1209", "가장 최근에 관용을 베푼 경험은?");
        questions.put("1210", "오늘 나를 놀라게 한 것은?");
        questions.put("1211", "현재 나의 몸무게는?");
        questions.put("1212", "로또에 당첨되면 가장 먼저 하고 싶은 일은?");
        questions.put("1213", "올초에 계획한 일 중에서 이루지 못한 것이 있다면?");
        questions.put("1214", "내가 대단한 이유는?");
        questions.put("1215", "모자람 vs 과함?");
        questions.put("1216", "거부할 수 없는 것은?");
        questions.put("1217", "새로운 곳으로 이사한다면 어느 도시로 가고 싶은가?");
        questions.put("1218", "변기에 앉아서 무슨 생각을 하는가?");
        questions.put("1219", "가장 오래 통화해본 기억은?");
        questions.put("1220", "내가 생각하는 환상적인 휴가는?");
        questions.put("1221", "몇 살까지 살고 싶은가?");
        questions.put("1222", "건강을 위해 꼭 챙겨먹는 음식이 있다면?");
        questions.put("1223", "마트에 가서 꼭 사는 물건은?");
        questions.put("1224", "산타클로스에게 받고 싶은 선물이 있다면?");
        questions.put("1225", "'크리스마스'로 오행시를 지어보자.");
        questions.put("1226", "오늘 얼마나 즉흥적으로 행동했는지 1에서 10으로 나타낸다면?");
        questions.put("1227", "내가 생각하는 가장 평화로운 장면은?");
        questions.put("1228", "집 안에서 뒹굴거리기 vs 밖에 나가서 놀기?");
        questions.put("1229", "소원 세 가지는?");
        questions.put("1230", "가장 최근에 잃어버린 물건이 있다면?");
        questions.put("1231", "올해 가장 기억에 남는 일은?");
    }

}
